In [2]:
import numpy as np
from qiskit import QuantumCircuit
from qiskit.quantum_info import Operator

# Create a single qubit quantum circuit
qc = QuantumCircuit(1)

# Apply the X gate (Pauli-X)
qc.x(0)

# Apply the Y gate (Pauli-Y)
qc.y(0)

# Apply the Z gate (Pauli-Z)
qc.z(0)

# Apply the H gate (Hadamard)
qc.h(0)

# Apply the S gate (Phase)
qc.s(0)

# Apply the Ry gate (Rotation around Y-axis)
theta = np.pi / 4  # You can change the value of theta as needed
qc.ry(theta, 0)

# Draw the circuit
print(qc)

# Convert the circuit to a unitary matrix (if needed)
backend = Aer.get_backend('unitary_simulator')
unitary = execute(qc, backend).result().get_unitary()

# Print out the unitary matrix
print("Unitary matrix of the circuit:")
print(unitary)


   ┌───┐┌───┐┌───┐┌───┐┌───┐┌─────────┐
q: ┤ X ├┤ Y ├┤ Z ├┤ H ├┤ S ├┤ Ry(π/4) ├
   └───┘└───┘└───┘└───┘└───┘└─────────┘


NameError: name 'Aer' is not defined

In [4]:
# get matrix of the gates
x_gate = Operator.from_label('X')

In [6]:
# convert to matrix
x_gate_matrix = x_gate.data

In [46]:
import numpy as np

# Define the angle theta for the Ry gate
theta = np.pi / 4  # Change this as needed for different rotations

# Pauli-X gate
X = np.array([[0, 1],
              [1, 0]], dtype=complex)

# Pauli-Y gate
Y = np.array([[0, -1j],
              [1j, 0]], dtype=complex)

# Pauli-Z gate
Z = np.array([[1, 0],
              [0, -1]], dtype=complex)

# Hadamard gate
H = np.array([[1, 1],
              [1, -1]], dtype=complex) / np.sqrt(2)

# S (phase) gate
S = np.array([[1, 0],
              [0, 1j]], dtype=complex)

# Ry (rotation around Y-axis) gate
Ry = np.array([[np.cos(theta / 2), -np.sin(theta / 2)],
               [np.sin(theta / 2), np.cos(theta / 2)]], dtype=complex)


# Rx gate matrix
Rx = np.array([
    [np.cos(theta/2), -1j * np.sin(theta/2)],
    [-1j * np.sin(theta/2), np.cos(theta/2)]
], dtype=complex)


# Print the arrays
print("X gate:\n", X)
print("\nY gate:\n", Y)
print("\nZ gate:\n", Z)
print("\nHadamard gate (H):\n", H)
print("\nS (phase) gate:\n", S)
print("\nRy gate for theta =", theta, ":\n", Ry)
print("\nRx gate for theta =", theta, ":\n", Rx)


X gate:
 [[0.+0.j 1.+0.j]
 [1.+0.j 0.+0.j]]

Y gate:
 [[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]

Z gate:
 [[ 1.+0.j  0.+0.j]
 [ 0.+0.j -1.+0.j]]

Hadamard gate (H):
 [[ 0.70710678+0.j  0.70710678+0.j]
 [ 0.70710678+0.j -0.70710678+0.j]]

S (phase) gate:
 [[1.+0.j 0.+0.j]
 [0.+0.j 0.+1.j]]

Ry gate for theta = 0.7853981633974483 :
 [[ 0.92387953+0.j -0.38268343+0.j]
 [ 0.38268343+0.j  0.92387953+0.j]]

Rx gate for theta = 0.7853981633974483 :
 [[0.92387953+0.j         0.        -0.38268343j]
 [0.        -0.38268343j 0.92387953+0.j        ]]


In [43]:
S @ Rx @ S

array([[ 0.92387953+0.j,  0.38268343+0.j],
       [ 0.38268343+0.j, -0.92387953+0.j]])

In [44]:
Rx@ S

array([[0.92387953+0.j        , 0.38268343+0.j        ],
       [0.        -0.38268343j, 0.        +0.92387953j]])

In [45]:
Rx

array([[0.92387953+0.j        , 0.        -0.38268343j],
       [0.        -0.38268343j, 0.92387953+0.j        ]])

In [38]:
S @ Ry @ S @ H @ X @ H

array([[0.70710678+2.29934717e-17j, 0.        +7.07106781e-01j],
       [0.        +7.07106781e-01j, 0.70710678+2.29934717e-17j]])

In [30]:
S @ Ry @ S

array([[ 0.70710678+0.j        ,  0.        -0.70710678j],
       [ 0.        +0.70710678j, -0.70710678+0.j        ]])

In [31]:
S @ Ry @ S @ H @ X@ H

array([[0.70710678+2.29934717e-17j, 0.        +7.07106781e-01j],
       [0.        +7.07106781e-01j, 0.70710678+2.29934717e-17j]])

In [32]:
Ry

array([[ 0.70710678+0.j, -0.70710678+0.j],
       [ 0.70710678+0.j,  0.70710678+0.j]])

In [48]:
Z@Rx@ Z

array([[0.92387953+0.j        , 0.        +0.38268343j],
       [0.        +0.38268343j, 0.92387953+0.j        ]])

In [49]:
Rx

array([[0.92387953+0.j        , 0.        -0.38268343j],
       [0.        -0.38268343j, 0.92387953+0.j        ]])

In [50]:
Rx@Z

array([[ 0.92387953+0.j        ,  0.        +0.38268343j],
       [ 0.        -0.38268343j, -0.92387953+0.j        ]])

In [51]:
Rx

array([[0.92387953+0.j        , 0.        -0.38268343j],
       [0.        -0.38268343j, 0.92387953+0.j        ]])

In [52]:
Rx@X

array([[0.        -0.38268343j, 0.92387953+0.j        ],
       [0.92387953+0.j        , 0.        -0.38268343j]])

In [53]:
Rx@Y

array([[ 0.38268343+0.j        ,  0.        -0.92387953j],
       [ 0.        +0.92387953j, -0.38268343+0.j        ]])

In [54]:
Rx

array([[0.92387953+0.j        , 0.        -0.38268343j],
       [0.        -0.38268343j, 0.92387953+0.j        ]])

In [55]:
Rx@X

array([[0.        -0.38268343j, 0.92387953+0.j        ],
       [0.92387953+0.j        , 0.        -0.38268343j]])

In [56]:
Y@ Z

array([[0.+0.j, 0.+1.j],
       [0.+1.j, 0.+0.j]])

In [58]:
H@S@Z@X

array([[0.        -0.70710678j, 0.70710678+0.j        ],
       [0.        +0.70710678j, 0.70710678+0.j        ]])